### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by niklasnisbeth** [nicklan/rust-jack#1]
I make a new project with cargo and add the dependency and get:

```
$ cargo build --verbose   
Compiling rust-jack v0.0.1 (https://github.com/nicklan/rust-jack.git#86fa24a8)
Running `rustc /home/niklas/.cargo/git/checkouts/rust-jack-77c4ac7b7014e954/master/src/lib.rs --crate-name jack --crate-type lib -g -C metadata=4783680d999c4de4 -C extra-filename=-4783680d999c4de4 --out-dir /home/niklas/code/rust-waveform/target/deps --emit=dep-info,link -L dependency=/home/niklas/code/rust-waveform/target/deps -L dependency=/home/niklas/code/rust-waveform/target/deps -Awarnings`
/home/niklas/.cargo/git/checkouts/rust-jack-77c4ac7b7014e954/master/src/lib.rs:3:14: 3:42 error: can't find crate for `rustc_bitflags`

/home/niklas/.cargo/git/checkouts/rust-jack-77c4ac7b7014e954/master/src/lib.rs:3 #[macro_use] extern crate rustc_bitflags;
```

Rust version: rustc 1.0.0-dev
Cargo version: cargo 0.0.1-pre-nightly (bb28e71 2015-01-22 06:06:34 +0000)

Any pointers?

**Comment by nicklan** [comment]
I suspect your version of rustc/cargo is out of date.  The bitflags macro was changed somewhat recently.  Can you try updating and let me know.  It compiles fine with the latest nightly on my end.

**Comment by nicklan** [comment]
Ohh shoot, just saw you listed your cargo/rustc version.  Hrmm, I build against rustc nightly, so that's probably the issue.

**Comment by niklasnisbeth** [comment]
That fixed it -- cheers!

**Comment by nicklan** [comment]
Sure, glad that worked!  And let me know if there's anything else you run into or any jack functionality you really need that I haven't got to yet.
